# spring.profiles.active=dev,test,custom
spring:
  datasource:
    url: jdbc:postgresql://dpg-cq3db5iju9rs739ctot0-a.frankfurt-postgres.render.com:5432/example_postgre_test
    username: example_postgre_test_user
    password: l4TWV19OeBdjrc2mkv4A4KWmINdO8gSI
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
